#!/usr/bin/env node
/**
 * kits/build.js — generate an Exit Kit for a self-hosted application.
 *
 * A kit takes someone from "the arithmetic says switch" to a running, backed-up,
 * restorable deployment. The part that makes it worth paying for is not the
 * compose file — anyone can write one — it is `restore-drill.sh`, which restores
 * the latest backup into a throwaway database and asserts the data is actually
 * there. Almost every self-hosting guide ships a backup script. Almost none ship
 * proof that the backup restores.
 *
 *   node kits/build.js [id ...]        generate into kits/out/exit-kit-<id>/
 *   node kits/build.js --verify        also check every pinned image tag resolves
 */

const fs = require('node:fs');
const path = require('node:path');

const OUT = path.join(__dirname, 'out');
const APPS = path.join(__dirname, 'apps');

const sub = (tpl, vars) => tpl.replace(/\{\{(\w+)\}\}/g, (_, k) => (k in vars ? vars[k] : `{{${k}}}`));

/* ------------------------------------------------------------------ compose */

function composeFile(s) {
  const db = s.database;
  return `# ${s.name} — generated by Exit Kit. Do not edit in place; edit the spec and regenerate.
#
# Postgres and Redis run as their own services rather than bundled into the app
# image. That is the whole reason this stack can be backed up and restored
# predictably: pg_dump against a real database beats copying a volume out from
# under a running process.

name: ${s.id}

services:
  db:
    image: ${s.images.db}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${db.name}
      POSTGRES_USER: ${db.user}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required — see .env.example}
      # Deterministic collation, so a restore onto a different host sorts identically.
      POSTGRES_INITDB_ARGS: "--locale=C --encoding=UTF8"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${db.user} -d ${db.name}"]
      interval: 10s
      timeout: 5s
      retries: 12
    # Never published to the host. Only the app network reaches the database.
    expose:
      - "5432"
    deploy:
      resources:
        limits:
          memory: 1g

  cache:
    image: ${s.images.cache}
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 6
    expose:
      - "6379"
    deploy:
      resources:
        limits:
          memory: 256m

  app:
    image: ${s.images.app}
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment:
      BASEROW_PUBLIC_URL: https://\${DOMAIN:?DOMAIN is required}
      DATABASE_HOST: db
      DATABASE_NAME: ${db.name}
      DATABASE_USER: ${db.user}
      DATABASE_PASSWORD: \${POSTGRES_PASSWORD}
      REDIS_HOST: cache
      SECRET_KEY: \${BASEROW_SECRET_KEY:?BASEROW_SECRET_KEY is required}
      BASEROW_JWT_SIGNING_KEY: \${BASEROW_JWT_SIGNING_KEY:?BASEROW_JWT_SIGNING_KEY is required}
    volumes:
      - app-data:${s.data_paths[0]}
    expose:
      - "${s.app_port}"
    deploy:
      resources:
        limits:
          memory: 2g

  proxy:
    image: ${s.images.proxy}
    restart: unless-stopped
    depends_on: [app]
    # The only two ports open to the world.
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN: \${DOMAIN:?DOMAIN is required}
      ACME_EMAIL: \${ACME_EMAIL:?ACME_EMAIL is required}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config

volumes:
  db-data:
  app-data:
  caddy-data:
  caddy-config:
`;
}

const caddyfile = (s) => `# TLS is obtained and renewed automatically. Point {$DOMAIN}'s A record at this
# server before starting, or the certificate request will fail.
{
	email {$ACME_EMAIL}
}

{$DOMAIN} {
	encode zstd gzip

	# Sensible defaults, not a compliance checklist.
	header {
		Strict-Transport-Security "max-age=31536000; includeSubDomains"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "SAMEORIGIN"
		Referrer-Policy "strict-origin-when-cross-origin"
		-Server
	}

	reverse_proxy app:${s.app_port}
}
`;

/* ------------------------------------------------------------------- env */

function envExample(s) {
  const lines = [
    `# ${s.name} — copy to .env and fill in. Never commit .env.`,
    `#`,
    `# Generate the secret values with:`,
    `#   openssl rand -base64 36 | tr -d '\\n'`,
    ``,
  ];
  for (const e of s.env) {
    lines.push(`# ${e.desc}`);
    if (e.generate) lines.push(`# Generate this — do not invent one by hand.`);
    lines.push(`${e.key}=${e.example || ''}`);
    lines.push('');
  }
  return lines.join('\n');
}

/* --------------------------------------------------------------- backup */

const backupSh = (s) => `#!/usr/bin/env bash
#
# ${s.name} backup. Runs a real pg_dump against a live database, archives the
# application's own data directory, encrypts both with a passphrase that lives
# somewhere other than this machine, and ships the result offsite.
#
# It refuses to report success it has not earned: every step is checked, and the
# script exits non-zero on any failure so cron will mail you.

set -Eeuo pipefail

cd "$(dirname "$0")"
[ -f .env ] || { echo "backup: no .env in $(pwd)" >&2; exit 1; }
set -a; . ./.env; set +a

: "\${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not set}"
: "\${BACKUP_PASSPHRASE:?BACKUP_PASSPHRASE not set}"
: "\${RCLONE_REMOTE:?RCLONE_REMOTE not set}"

STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "backup: starting \${STAMP}"

# --- database -----------------------------------------------------------------
# --clean --if-exists so the dump can be replayed onto a non-empty database,
# which is what the restore drill does every night.
docker compose exec -T -e PGPASSWORD="\$POSTGRES_PASSWORD" db \\
  pg_dump --username="${s.database.user}" --dbname="${s.database.name}" \\
          --format=custom --clean --if-exists \\
  > "\$WORK/db.dump"

DB_BYTES=$(stat -c%s "\$WORK/db.dump")
# A dump smaller than this is not a database, it is an error message.
if [ "\$DB_BYTES" -lt 5000 ]; then
  echo "backup: database dump is only \${DB_BYTES} bytes — refusing to treat that as a backup" >&2
  exit 1
fi
echo "backup: database dumped (\${DB_BYTES} bytes)"

# --- application data ---------------------------------------------------------
docker compose exec -T app tar -C "${s.data_paths[0]}" -cf - . > "\$WORK/data.tar" 2>/dev/null \\
  || { echo "backup: failed to archive ${s.data_paths[0]}" >&2; exit 1; }
echo "backup: data directory archived ($(stat -c%s "\$WORK/data.tar") bytes)"

# --- package and encrypt ------------------------------------------------------
printf '%s\\n' "\$STAMP" > "\$WORK/STAMP"
tar -C "\$WORK" -czf "\$WORK/bundle.tar.gz" db.dump data.tar STAMP

# Symmetric AES-256. The passphrase is never written to disk.
openssl enc -aes-256-cbc -pbkdf2 -iter 200000 -salt \\
  -in "\$WORK/bundle.tar.gz" -out "\$WORK/\${STAMP}.tar.gz.enc" \\
  -pass env:BACKUP_PASSPHRASE
echo "backup: encrypted"

# --- ship it ------------------------------------------------------------------
rclone copy "\$WORK/\${STAMP}.tar.gz.enc" "\$RCLONE_REMOTE/" --no-traverse
echo "backup: uploaded to \$RCLONE_REMOTE/\${STAMP}.tar.gz.enc"

# --- retention ----------------------------------------------------------------
# Keep 14 days. Deliberately deletes only what is older than that, and only
# files matching our own naming, so it cannot eat a bucket it shares.
rclone delete "\$RCLONE_REMOTE/" --min-age 14d --include "*.tar.gz.enc"
echo "backup: retention applied (14 days)"

echo "backup: done"
`;

/* ---------------------------------------------------- the restore drill */

const restoreDrillSh = (s) => {
  const assertions = s.restore_assertions.map((a) => `
run_assertion "${a.label}" "${a.sql.replace(/"/g, '\\"')}" ${a.min}`).join('');

  return `#!/usr/bin/env bash
#
# ${s.name} restore drill — the reason this kit exists.
#
# A backup you have never restored is a hope, not a backup. This script takes the
# most recent backup from the offsite bucket, restores it into a THROWAWAY
# database container that is not part of your stack, runs assertions against the
# restored data, and destroys it.
#
# It never touches your live database. It exits non-zero if the restore did not
# produce data you would actually want back, so running it from cron means you
# hear about a broken backup on a Tuesday rather than during an outage.

set -Eeuo pipefail

cd "$(dirname "$0")"
[ -f .env ] || { echo "drill: no .env in $(pwd)" >&2; exit 1; }
set -a; . ./.env; set +a

: "\${BACKUP_PASSPHRASE:?BACKUP_PASSPHRASE not set}"
: "\${RCLONE_REMOTE:?RCLONE_REMOTE not set}"

DRILL_DB="${s.id}-restore-drill"
DRILL_PW="drill-$(openssl rand -hex 8)"
WORK="$(mktemp -d)"
FAILURES=0

cleanup() {
  docker rm -f "\$DRILL_DB" >/dev/null 2>&1 || true
  rm -rf "\$WORK"
}
trap cleanup EXIT

echo "drill: starting"

# --- fetch the most recent backup --------------------------------------------
LATEST="$(rclone lsf "\$RCLONE_REMOTE/" --include '*.tar.gz.enc' | sort | tail -n1)"
[ -n "\$LATEST" ] || { echo "drill: FAIL — no backups found at \$RCLONE_REMOTE" >&2; exit 1; }
echo "drill: newest backup is \$LATEST"

# A backup nobody has written for days is itself a failure, even if it restores.
AGE_DAYS=$(( ( $(date -u +%s) - $(date -u -d "$(echo "\$LATEST" | sed -E 's/^([0-9]{8})T([0-9]{6})Z.*/\\1 \\2/' | sed -E 's/^(....)(..)(..) (..)(..)(..)$/\\1-\\2-\\3 \\4:\\5:\\6/')" +%s) ) / 86400 ))
if [ "\$AGE_DAYS" -gt 2 ]; then
  echo "drill: FAIL — newest backup is \${AGE_DAYS} days old; the backup job is not running" >&2
  FAILURES=$((FAILURES + 1))
fi

rclone copy "\$RCLONE_REMOTE/\$LATEST" "\$WORK/" --no-traverse

# --- decrypt and unpack -------------------------------------------------------
openssl enc -d -aes-256-cbc -pbkdf2 -iter 200000 \\
  -in "\$WORK/\$LATEST" -out "\$WORK/bundle.tar.gz" -pass env:BACKUP_PASSPHRASE \\
  || { echo "drill: FAIL — could not decrypt. Wrong BACKUP_PASSPHRASE, or a corrupt file." >&2; exit 1; }

tar -C "\$WORK" -xzf "\$WORK/bundle.tar.gz" \\
  || { echo "drill: FAIL — the decrypted bundle is not a readable archive" >&2; exit 1; }
[ -s "\$WORK/db.dump" ] || { echo "drill: FAIL — no database dump inside the backup" >&2; exit 1; }
echo "drill: decrypted and unpacked ($(stat -c%s "\$WORK/db.dump") bytes of database)"

# --- restore into a container that is not your stack --------------------------
docker run -d --name "\$DRILL_DB" \\
  -e POSTGRES_PASSWORD="\$DRILL_PW" \\
  -e POSTGRES_USER="${s.database.user}" \\
  -e POSTGRES_DB="${s.database.name}" \\
  -e POSTGRES_INITDB_ARGS="--locale=C --encoding=UTF8" \\
  ${s.images.db} >/dev/null

printf 'drill: waiting for the throwaway database'
for _ in $(seq 1 60); do
  if docker exec "\$DRILL_DB" pg_isready -U "${s.database.user}" -d "${s.database.name}" >/dev/null 2>&1; then
    echo " ready"; break
  fi
  printf '.'; sleep 1
done
docker exec "\$DRILL_DB" pg_isready -U "${s.database.user}" -d "${s.database.name}" >/dev/null 2>&1 \\
  || { echo; echo "drill: FAIL — the throwaway database never came up" >&2; exit 1; }

docker cp "\$WORK/db.dump" "\$DRILL_DB:/tmp/db.dump"
# --exit-on-error so a partially-restorable dump counts as a failure, which is
# the honest reading: a half-restored database is not a recovery.
docker exec -e PGPASSWORD="\$DRILL_PW" "\$DRILL_DB" \\
  pg_restore --username="${s.database.user}" --dbname="${s.database.name}" \\
             --clean --if-exists --exit-on-error /tmp/db.dump \\
  || { echo "drill: FAIL — pg_restore could not replay the dump" >&2; exit 1; }
echo "drill: restored"

# --- assert the data is actually there ----------------------------------------
run_assertion() {
  local label="\$1" sql="\$2" min="\$3" got
  got=$(docker exec -e PGPASSWORD="\$DRILL_PW" "\$DRILL_DB" \\
        psql -U "${s.database.user}" -d "${s.database.name}" -tAc "\$sql" 2>/dev/null || echo "ERR")
  if [ "\$got" = "ERR" ]; then
    echo "  FAIL  \$label — query failed against the restored database"
    FAILURES=$((FAILURES + 1))
  elif [ "\$got" -lt "\$min" ]; then
    echo "  FAIL  \$label — got \$got, expected at least \$min"
    FAILURES=$((FAILURES + 1))
  else
    echo "  ok    \$label (\$got)"
  fi
}
${assertions}

# --- verdict ------------------------------------------------------------------
if [ "\$FAILURES" -gt 0 ]; then
  echo
  echo "drill: FAILED — \$FAILURES check(s) did not pass. Your backup would not have saved you." >&2
  exit 1
fi

echo
echo "drill: PASSED — \$LATEST restores cleanly and contains real data."
`;
};

/* -------------------------------------------------------------- install */

const installSh = (s) => `#!/usr/bin/env bash
#
# Prepares a fresh Debian or Ubuntu server for ${s.name} and starts it.
# Safe to re-run: every step checks before it acts.

set -Eeuo pipefail

[ "$(id -u)" -eq 0 ] || { echo "install: run as root (sudo -i)" >&2; exit 1; }
cd "$(dirname "$0")"

echo "==> packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq ca-certificates curl gnupg ufw unattended-upgrades rclone openssl

echo "==> docker"
if ! command -v docker >/dev/null 2>&1; then
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "\$VERSION_CODENAME") stable" \\
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
fi
docker --version

echo "==> unattended security updates"
# Security patches are the maintenance hour this whole comparison charges you for.
# Letting the machine apply them itself is how you actually spend fewer of them.
dpkg-reconfigure -f noninteractive unattended-upgrades

echo "==> firewall"
ufw allow 22/tcp   >/dev/null
ufw allow 80/tcp   >/dev/null
ufw allow 443/tcp  >/dev/null
ufw --force enable >/dev/null
ufw status verbose | sed 's/^/    /'

echo "==> configuration"
if [ ! -f .env ]; then
  echo "install: no .env yet."
  echo "         cp .env.example .env, fill it in, then run this again."
  exit 1
fi
set -a; . ./.env; set +a
: "\${DOMAIN:?DOMAIN is not set in .env}"
: "\${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is not set in .env}"

echo "==> starting ${s.name}"
docker compose pull
docker compose up -d

echo
echo "${s.name} is starting. First boot runs database migrations and can take"
echo "several minutes. Watch it with:  docker compose logs -f app"
echo
echo "Then, in order:"
echo "  1. point \${DOMAIN} at this server's IP address"
echo "  2. ./backup.sh          — take the first backup by hand"
echo "  3. ./restore-drill.sh   — prove that backup actually restores"
echo "  4. crontab -e           — see crontab.example"
`;

const crontabExample = (s) => `# ${s.name} — Exit Kit schedule.
#
# The drill runs an hour after the backup, so a broken backup is caught the same
# night. If either fails, cron mails the output to the machine's user; make sure
# that mail actually reaches you before you rely on it.

15 3 * * *  cd ${'{{KITDIR}}'} && ./backup.sh        >> /var/log/${s.id}-backup.log 2>&1
15 4 * * *  cd ${'{{KITDIR}}'} && ./restore-drill.sh >> /var/log/${s.id}-drill.log  2>&1

# Weekly image updates. Review the release notes first — this pulls whatever the
# pinned tag now points at, and pinned tags can be re-pushed.
# 30 4 * * 0  cd ${'{{KITDIR}}'} && docker compose pull && docker compose up -d
`;

/* ---------------------------------------------------------------- README */

const readme = (s) => `# Exit Kit — ${s.name}

Everything needed to run ${s.name} in place of ${s.replaces}, back it up, and
know the backup works.

## What is in here

| File | What it does |
|---|---|
| \`install.sh\` | Prepares a fresh Debian/Ubuntu server: Docker, firewall, automatic security updates, then starts the stack. Safe to re-run. |
| \`docker-compose.yml\` | The stack. Pinned images, no default passwords, health checks, memory limits, and only ports 80 and 443 exposed. |
| \`.env.example\` | Every setting, with what it is for. |
| \`Caddyfile\` | TLS, obtained and renewed automatically. |
| \`backup.sh\` | Real \`pg_dump\` plus the data directory, encrypted before it leaves the machine, shipped offsite, 14-day retention. |
| \`restore-drill.sh\` | **Restores the latest backup into a throwaway database and asserts the data is there.** |
| \`RUNBOOK.md\` | Upgrades, what to watch, and what to do when it breaks. |
| \`crontab.example\` | Nightly backup, nightly drill. |

## Why the restore drill is the point

Most self-hosting guides give you a backup script. Almost none give you a way to
find out whether it works. The failure everyone actually has is not "I had no
backups" — it is "I had backups and they were empty, or truncated, or encrypted
with a passphrase I no longer had".

\`restore-drill.sh\` runs every night, an hour after the backup:

1. Pulls the newest backup out of your bucket
2. Fails if it is more than two days old — a stale backup is a broken backup
3. Decrypts it, and fails loudly if the passphrase is wrong
4. Starts a **throwaway** Postgres container, entirely separate from your stack
5. Replays the dump with \`--exit-on-error\`, so a partial restore counts as a failure
6. Runs assertions against the restored data:
${s.restore_assertions.map((a) => `   - ${a.label} (at least ${a.min})`).join('\n')}
7. Destroys the container and exits non-zero if anything failed

Your live database is never touched. You find out on a Tuesday, not during an outage.

## Getting started

\`\`\`sh
cp .env.example .env
$EDITOR .env                 # generate the secrets: openssl rand -base64 36
sudo ./install.sh
\`\`\`

Then point your domain at the server, run \`./backup.sh\` once by hand, run
\`./restore-drill.sh\` to prove it, and install the cron entries.

## What this kit does not do

Stated plainly, because the comparison that sent you here charges you for the
hours this software costs and it would be dishonest to pretend they are zero.

- **It is one server.** No high availability. If the machine dies you restore
  onto a new one from a backup — which is exactly why the drill matters.
- **It does not monitor uptime.** Point any external checker at your domain.
- **It does not manage your DNS or your domain.**
- **It does not make you exempt from reading release notes** before an upgrade.

${s.notes.map((n) => `> ${n}`).join('\n>\n')}

## Requirements

${s.requirements.vcpu} vCPU, ${s.requirements.ram_gb} GB RAM, ${s.requirements.disk_gb} GB disk, and a domain name.
Upstream documentation: ${s.docs}
`;

const runbook = (s) => `# ${s.name} runbook

## Every day, without you

- 03:15 — \`backup.sh\` dumps the database and archives the data directory,
  encrypts both, ships them offsite, and prunes anything older than 14 days.
- 04:15 — \`restore-drill.sh\` proves the newest backup restores. If it does not,
  cron mails you the failure.

## Upgrading

\`\`\`sh
# 1. Read the release notes. This is not optional for a database-backed app.
# 2. Take a backup you can name.
./backup.sh

# 3. Prove it before you touch anything.
./restore-drill.sh

# 4. Change the tag in docker-compose.yml, then:
docker compose pull
docker compose up -d
docker compose logs -f app
\`\`\`

If the new version fails to start, roll the tag back and \`docker compose up -d\`.
Your data is untouched — the database volume is separate from the app image.

## When something is wrong

**The site is down.**
\`\`\`sh
docker compose ps            # which service is unhealthy?
docker compose logs --tail=200 app
docker compose logs --tail=50 proxy
\`\`\`

**TLS is failing.** Caddy needs port 80 reachable from the internet to renew.
Check \`ufw status\` and that your DNS A record still points here.

**The database will not start.** Look for a disk-full condition first — it is the
most common cause and the least obvious: \`df -h\`.

**You need to actually restore.** The drill script is the rehearsal; a real
restore is the same steps against your live stack:
\`\`\`sh
docker compose stop app
rclone copy "$RCLONE_REMOTE/<the-backup>" .
openssl enc -d -aes-256-cbc -pbkdf2 -iter 200000 -in <the-backup> -out bundle.tar.gz -pass env:BACKUP_PASSPHRASE
tar -xzf bundle.tar.gz
docker compose exec -T db pg_restore -U ${s.database.user} -d ${s.database.name} --clean --if-exists --exit-on-error < db.dump
docker compose start app
\`\`\`

## What to watch

- Disk usage. \`${s.name}\` grows with attachments; the drill will not warn you
  about a full disk.
- The drill's own exit status. If it stops mailing you, it stopped running.
- \`BACKUP_PASSPHRASE\` must exist somewhere that is **not this server**. If the
  server is gone and the passphrase was only on it, the backups are noise.
`;

/* ------------------------------------------------------------------- main */

function generate(spec) {
  const dir = path.join(OUT, `exit-kit-${spec.id}`);
  fs.mkdirSync(dir, { recursive: true });

  const files = {
    'docker-compose.yml': composeFile(spec),
    'Caddyfile': caddyfile(spec),
    '.env.example': envExample(spec),
    'install.sh': installSh(spec),
    'backup.sh': backupSh(spec),
    'restore-drill.sh': restoreDrillSh(spec),
    'crontab.example': sub(crontabExample(spec), { KITDIR: `/opt/exit-kit-${spec.id}` }),
    'README.md': readme(spec),
    'RUNBOOK.md': runbook(spec),
  };

  for (const [name, body] of Object.entries(files)) {
    const f = path.join(dir, name);
    fs.writeFileSync(f, body, 'utf8');
    if (name.endsWith('.sh')) fs.chmodSync(f, 0o755);
  }
  return { dir, files: Object.keys(files), images: Object.values(spec.images) };
}

async function main() {
  const args = process.argv.slice(2);
  const verify = args.includes('--verify');
  const only = args.filter((a) => !a.startsWith('--'));

  let specs = fs.readdirSync(APPS).filter((f) => f.endsWith('.json'))
    .map((f) => JSON.parse(fs.readFileSync(path.join(APPS, f), 'utf8')));
  if (only.length) specs = specs.filter((s) => only.includes(s.id));
  if (!specs.length) { console.error('no kit specs matched'); process.exit(1); }

  const allImages = [];
  for (const s of specs) {
    const r = generate(s);
    allImages.push(...r.images);
    console.log(`built exit-kit-${s.id}: ${r.files.length} files -> ${path.relative(process.cwd(), r.dir)}`);
  }

  if (verify) {
    const { verifyAll } = require('./lib/verify-images.js');
    console.log('\nverifying pinned image tags:');
    const v = await verifyAll(allImages);
    for (const r of v.results) {
      console.log(`  ${r.exists ? 'ok  ' : r.checked ? 'MISS' : 'skip'}  ${r.ref.padEnd(28)} ${r.last_pushed ? 'pushed ' + r.last_pushed.slice(0, 10) : (r.reason || '')}`);
    }
    if (!v.ok) { console.error(`\nFATAL: ${v.missing.length} image tag(s) do not exist: ${v.missing.join(', ')}`); process.exit(1); }
    console.log(`\nall ${v.results.length} image tags resolve`);
  }
}

if (require.main === module) main().catch((e) => { console.error(e); process.exit(1); });
module.exports = { generate, composeFile, envExample };
